'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Senarai_Objek_Am
    
    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''ddlKodKW control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlKodKW As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlObjekAm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlObjekAm As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''rbStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbStatus As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''lbtnSimpan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnSimpan As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbtnHapus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnHapus As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbtnBaru control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnBaru As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lblJumRekod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJumRekod As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''gvObjekAm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvObjekAm As Global.System.Web.UI.WebControls.GridView
End Class
