'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class testAirv4

    '''<summary>
    '''gvMaklumatKorporat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvMaklumatKorporat As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''txtSingkatan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSingkatan As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''imgMyImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgMyImage As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''fileUploadControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fileUploadControl As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''btnUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpload As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtNama control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNama As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAlamat1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAlamat1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtAlamat2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAlamat2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtBandar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBandar As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtPoskod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPoskod As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtTel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTel1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtNegeri control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNegeri As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtTel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTel2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtNegara control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNegara As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtFaks1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFaks1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtWeb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWeb As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtEmel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmel As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''lbtnSimpan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnSimpan As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''lblModalMessaage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModalMessaage As Global.System.Web.UI.WebControls.Label
End Class
