'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Kod_Kawalan_Pinjaman
    
    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''TabContainer1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabContainer1 As Global.AjaxControlToolkit.TabContainer
    
    '''<summary>
    '''tabModul control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabModul As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''txtKodKat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKodKat As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtButiranKat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtButiranKat As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lbtnSimpanKatPinj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnSimpanKatPinj As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbtnHapusModul control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnHapusModul As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbtnBaru control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnBaru As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lblJumMod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJumMod As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ddlSaizRekod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSaizRekod As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''gvKatPinj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvKatPinj As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''tabJenPinj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabJenPinj As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''txtKodJenPinj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKodJenPinj As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtButirJenPinj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtButirJenPinj As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lbtnSimpanJenPinj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnSimpanJenPinj As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbtnHapusJenPinj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnHapusJenPinj As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbtnBaruJenPinj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnBaruJenPinj As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lblJumSubMod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJumSubMod As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ddlSaizRekodJenPinj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSaizRekodJenPinj As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''gvJenPinj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvJenPinj As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''tabKdrTempoh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabKdrTempoh As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''txtKodKdrTempoh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKodKdrTempoh As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtButirKdrTempoh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtButirKdrTempoh As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lbtnSimpanKdrTempoh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnSimpanKdrTempoh As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbtnHapusKdrTempoh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnHapusKdrTempoh As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbtnBaruKdrTempoh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnBaruKdrTempoh As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lblJumKdrTempoh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJumKdrTempoh As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ddlSaizRekodKdrTempoh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSaizRekodKdrTempoh As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''gvKdrTempoh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvKdrTempoh As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''tabSkimPinj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabSkimPinj As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''txtKodSkimPinj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKodSkimPinj As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtButirSkimPinj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtButirSkimPinj As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lbtnSimpanSkimPinj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnSimpanSkimPinj As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbtnHapusSkimPinj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnHapusSkimPinj As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbtnBaruSkimPinj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnBaruSkimPinj As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DropDownList1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownList1 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''gvSkimPinj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvSkimPinj As Global.System.Web.UI.WebControls.GridView
End Class
