'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class summary2_ABM7
    
    '''<summary>
    '''lblCetak control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCetak As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lblCetakdS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCetakdS As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lblCetakdB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCetakdB As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lblCetakoff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCetakoff As Global.System.Web.UI.WebControls.LinkButton
End Class
