'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Senarai_Kelulusan1
    
    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''txtTahun control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTahun As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlPTJ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPTJ As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblJumRekod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJumRekod As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''gvViremen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvViremen As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''txtNoViremen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNoViremen As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtTkhMohon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTkhMohon As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtKodKWF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKodKWF As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtKwF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKwF As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtKodKoF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKodKoF As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtKoF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKoF As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtKodPTjF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKodPTjF As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPTjF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPTjF As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtKodKPF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKodKPF As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtKPF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKPF As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtKodSbgF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKodSbgF As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtObjSbgF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtObjSbgF As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAmaunF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAmaunF As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtBakiF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBakiF As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtKodKWT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKodKWT As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtKWT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKWT As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtKodKoT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKodKoT As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtKoT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKoT As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtKodPTjT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKodPTjT As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPTjT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPTjT As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtKodKpT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKodKpT As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtKpT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKpT As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtKodSbgT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKodSbgT As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtObjSbgT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtObjSbgT As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAmaunT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAmaunT As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtBakiT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBakiT As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtNoStaf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNoStaf As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtNamaStaf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNamaStaf As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtJawatan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtJawatan As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtkodPTjPemohon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtkodPTjPemohon As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPTjPemohon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPTjPemohon As Global.System.Web.UI.WebControls.TextBox
End Class
