'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Agihan_Objek_Am
    
    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''ddlTahunAgih control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTahunAgih As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlKW control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlKW As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlPTj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPTj As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtJumBajetPTj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtJumBajetPTj As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtJumAgihPTj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtJumAgihPTj As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''hidAgihPTj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidAgihPTj As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''txtJumBakiPTj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtJumBakiPTj As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlKO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlKO As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlKp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlKp As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtJumBajetKp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtJumBajetKp As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''hidBajetKp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidBajetKp As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''txtTBKp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTBKp As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtKGKp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKGKp As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtBFKp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBFKp As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtJumKp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtJumKp As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAgihanKp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAgihanKp As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtBakiKp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBakiKp As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblJumRekod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJumRekod As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''gvObjAm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvObjAm As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''lbtnSimpan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnSimpan As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''UpdateProgress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateProgress1 As Global.System.Web.UI.UpdateProgress
End Class
