'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PEMBATALAN_INVOIS_KEWANGAN
    
    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''divList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divList As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ddlCarian control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCarian As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtCarian control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCarian As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lbtnCari control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnCari As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lblJumRekod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJumRekod As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ddlSaizRekod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSaizRekod As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlFilStat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFilStat As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''gvLst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvLst As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''divDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divDetail As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lbtnKembali control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnKembali As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lblNoInv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoInv As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTkhMhn2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTkhMhn2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtNoJurnSem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNoJurnSem As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblTkhInv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTkhInv As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStatus As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblKodPtj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKodPtj As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNPTJ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNPTJ As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblKodBank control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKodBank As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNmBank control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNmBank As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblAlmt1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAlmt1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblKodKat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKodKat As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblKat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKat As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblAlmt2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAlmt2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNmPen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNmPen As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblKodNegeri control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKodNegeri As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNegeri control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNegeri As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblIdPen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIdPen As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblKodNegara control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKodNegara As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNegara control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNegara As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTujuan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTujuan As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBandar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBandar As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPoskod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPoskod As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPerhatian control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPerhatian As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNoTel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoTel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNoFax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoFax As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNoRuj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoRuj As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblEmel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblJenKontrak control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJenKontrak As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTkhMulaKon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTkhMulaKon As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTkhTamatKon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTkhTamatKon As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTemKon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTemKon As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblJenTem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJenTem As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TabContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabContainer As Global.AjaxControlToolkit.TabContainer
    
    '''<summary>
    '''tabTransAsl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabTransAsl As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''gvTransAsl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvTransAsl As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''tabTransLej control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabTransLej As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''gvTransLej control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvTransLej As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''lblNoStaf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoStaf As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNama control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNama As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblJwtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJwtn As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblKodPTjPenyedia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKodPTjPenyedia As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNamaPTjPenyedia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNamaPTjPenyedia As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTarikh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTarikh As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbtnBatal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnBatal As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''UpdateProgress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateProgress1 As Global.System.Web.UI.UpdateProgress
End Class
