'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Proses_Gaji

    '''<summary>
    '''ddlPtjDr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPtjDr As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlPtjHg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPtjHg As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlStafDr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlStafDr As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlStafHg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlStafHg As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblModalMessaage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModalMessaage As Global.System.Web.UI.WebControls.Label
End Class
